name: Cronus
main: ink.ptms.cronus.Cronus
version: 1.0.0.2019.8.2 beta 1
api-version: 1.13

author: 坏黑

soft-depend:
- Citizens
- Shopkeeper
- MythicMobs
- Skript
- SkillAPI
- WorldEdit
- WorldGuard
- PlaceholderAPI
- Vault
- SacredItem
- PurtmarsItem